package utils;

/**
 * The Enum OpEnum.
 */
public enum OpEnum {

	E_SELECT, E_UPDATE, E_LOGIN, E_REST_INFO, E_GET_MENU, E_BUSINESS_AMNT_USED, E_ADD_ORDER
	, E_GET_BUSINESS_COLLEAGUES, E_UPDATE_GROUP_ORDER, E_REPORTS_DATA, E_GET_RESTAURANT_ORDERS, E_RESTAURANT_APPROVE_ORDER,
	E_UPDATE_DISH, E_DELETE_DISH, E_GET_SPECIFIC_RESTAURANT, E_RESTAURANT_ORDER_READY, E_NOTIFY_CLIENT_ORDER_APPROVED, 
	E_NOTIFY_CLIENT_ORDER_IN_ROUTE, E_CLIENT_ORDER_RECIEVED, E_RESTAURANT_ORDER_RECIEVED, E_GET_BUSINESS,
	E_INSERT_NEW_BUSINESS,E_GETALLUSERS, E_BRING_REPORTS, E_GET_ALL_RESTID, E_GET_REST_REPORTS,
	E_NOTIFY_REST_OF_NEW_ORDER, E_UPDATE_LOGIN, E_GET_OPEN_ORDERS, E_GET_ALL_ORDERS_THIS_MONTH,
	E_GET_BUSINESS_LIST, E_INSERT_NEW_RESTAURANT, E_GET_ALL_USER_ORDERS, E_GET_REST_COMMISSIONS,
	E_GET_REPORTS_FOR_QUATERLY, E_INSERT_USER, E_UPDATE_USER_TO_RESTAURANT, E_INSERT_BUSINESS_USER, E_INSERT_HR_USER,
	E_UPDATE_USER, E_UPDATE_HR, E_SAVE_QUARTERLY_REPORT, E_GET_QUARTERLY_REPORT,E_SET_W4C_FOR_HR,E_GET_USERS_IN_ORDER_GRUOP,
	E_BRANCHMAN_TO_CEO_REPORT, E_GET_BRANCHMAN_TO_CEO_REPORTS;




}
